jobs:
  deploy_android:
    needs: [prepare_deploy]
    env:
      MULTIPLATFORM_KICKSTARTER_APP_VERSION_NAME: ${{ needs.prepare_deploy.outputs.output_write_multiplatform_kickstarter_version_name }}
      MULTIPLATFORM_KICKSTARTER_APP_VERSION_CODE: ${{ needs.prepare_deploy.outputs.output_write_multiplatform_kickstarter_version_code }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
      - name: "Build bundle release"
        run: gradle android:bundleRelease
      - uses: r0adkll/sign-android-release@v1
        name: "Sign app aab file"
        id: sign_app
        with:
          releaseDirectory: androidApp/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.MULTIPLATFORM_KICKSTARTER_ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.MULTIPLATFORM_KICKSTARTER_ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.MULTIPLATFORM_KICKSTARTER_ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.MULTIPLATFORM_KICKSTARTER_ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - uses: actions/upload-artifact@v3
        with:
          name: "Upload AAB file as artifact"
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: "Upload to Google Play"
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.MULTIPLATFORM_KICKSTARTER_ANDROID_DEPLOY_SERVICE_ACCOUNT_JSON }}
          packageName: com.multiplatformkickstarter.app.android
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: production
          status: completed